POST http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries HTTP/1.1
Content-Type: application/json

{
  "type": "OccupationalHealthcare",
  "description": "Description",
  "date": "2020-12-12",
  "specialist": "very special",
  "employerName": "NASA",
  "sickLeave": {
    "startDate": "2020-12-12",
    "endDate": "2020-12-25"
  }
}
