POST http://localhost:3001/api/patients HTTP/1.1
Content-Type: application/json

{
      "name": "hgf",
      "dateOfBirth": "1979-01-30",
      "ssn": "",
      "gender": "male",
      "occupation": "Robot"
  }
